Models/ApplicationUser.cs
using Microsoft.AspNetCore.Identity;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ciel.Models
{
    public class ApplicationUser : IdentityUser
    {
        [Required]
        [MaxLength(64)]
        [Display(Name = "Име")]
        public string Name { get; set; }

        [Required]
        [MaxLength(30)]
        [Display(Name = "Фамилия")]
        public string LastName { get; set; }

        [MaxLength(10)]
        [Required]
        [Display(Name = "ЕГН")]
        public string EGN { get; set; }
    }
}

Areas/Admin/Controllers/ApplicationUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Ciel.Data;
using Ciel.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Runtime.InteropServices;

namespace Ciel.Areas.Admin.Controllers
{
    [Area("Admin")]

    [Authorize(Roles = "Admin")]
    public class ApplicationUserController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public ApplicationUserController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _context = context;

            _userManager = userManager;
            _roleManager = roleManager;
        }
        // GET: Users
        public async Task<IActionResult> Index()
        {
            var currentUser = await _userManager.GetUserAsync(HttpContext.User);
            var users = await _context.ApplicationUsers

                .Where(u => u.Id != currentUser.Id)
                .ToListAsync();

            return View(users);
        }
        // GET: Users/Details/5
        public async Task<IActionResult> Details(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var user = await _context.ApplicationUsers

                .FirstOrDefaultAsync(m => m.Id == id);

            ViewData["userId"] = id;

            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ApplicationUser applicationUser, string password)
        {
            if (ModelState.IsValid)
            {
                if (string.IsNullOrWhiteSpace(password))
                {
                    ModelState.AddModelError("Password", "Паролата е задължителна.");
                    return View(applicationUser);
                }

                var user = new ApplicationUser
                {
                    Name = applicationUser.Name,
                    LastName = applicationUser.LastName,
                    Email = applicationUser.Email,
                    NormalizedEmail = applicationUser.NormalizedEmail?.ToUpper(),
                    UserName = applicationUser.UserName,
                    NormalizedUserName = applicationUser.UserName?.ToUpper(),
                    PhoneNumber = applicationUser.PhoneNumber,
                    EGN = applicationUser.EGN
                };

                var result = await _userManager.CreateAsync(user, password);

                if (result.Succeeded)
                {
                    // Проверка и добавяне на ролята "ApplicationUser" на потребителя
                    if (!await _roleManager.RoleExistsAsync("Customer"))
                    {
                        await _roleManager.CreateAsync(new IdentityRole("Customer"));
                    }

                    await _userManager.AddToRoleAsync(user, "Customer");

                    // Създаване на карта за потребителя
                    var cart = new Cart { UserId = user.Id };
                    _context.Carts.Add(cart);
                    await _context.SaveChangesAsync();

                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(applicationUser);
        }
        public async Task<IActionResult> Edit(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Редактиране/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, ApplicationUser model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var user = await _userManager.FindByIdAsync(id);
                    if (user == null)
                    {
                        return NotFound();
                    }

                    //Актуализиране на потребителските свойства
                    user.Name = model.Name;
                    user.LastName = model.LastName;
                    user.Email = model.Email;
                    user.UserName = model.UserName;
                    user.PhoneNumber = model.PhoneNumber;
                    user.EGN = model.EGN;

                    //Актуализиране на потребителя в базата данни
                    var result = await _userManager.UpdateAsync(user);

                    if (result.Succeeded)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError("", error.Description);
                        }
                        return View(model);
                    }
                }
                catch (Exception)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(model);
        }
        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(string id)
        {
            var user = await _context.ApplicationUsers.FindAsync(id);

            _context.ApplicationUsers.Remove(user);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

Areas/Admin/Views/ApplicationUser/Create.cshtml
@model Ciel.Models.ApplicationUser
@{
    ViewData["Title"] = "Създаване на нов потребител";
}
<div class="text-center mb-4">
    <h1 class="styled-header">Създай потребител</h1>
</div>

<form asp-action="Create" enctype="multipart/form-data" class="col-md-6 offset-md-3">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Name" class="font-weight-bold">Име</label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="LastName" class="font-weight-bold">Фамилия</label>
        <input asp-for="LastName" class="form-control" />
        <span asp-validation-for="LastName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="UserName" class="font-weight-bold">Потребителско Име</label>
        <input asp-for="UserName" class="form-control" />
        <span asp-validation-for="UserName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Email" class="font-weight-bold">Имейл</label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="PhoneNumber" class="font-weight-bold">Телефонен Номер</label>
        <input asp-for="PhoneNumber" class="form-control" />
        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="EGN" class="font-weight-bold">ЕГН</label>
        <input asp-for="EGN" class="form-control" />
        <span asp-validation-for="EGN" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="PasswordHash" class="font-weight-bold">Парола</label>
        <input type="password" id="Password" name="Password" class="form-control" />
        <span asp-validation-for="PasswordHash" class="text-danger"></span>
    </div>
    <div class="text-center">
        <button type="submit" class="btn btn-secondary"> <i class="bi bi-person-plus"></i> Добави</button>
        <a asp-action="Index" class="btn btn-secondary ml-2"> <i class="bi bi-arrow-bar-left"></i> Назад</a>
    </div>
</form>
<div style="height: 50px;"></div>

Areas/Admin/Views/ApplicationUser/Delete.cshtml
@model Ciel.Models.ApplicationUser

@{

    ViewData["Title"] = "Детайли-потребител";

}

<br />
<h1>Изтриване на потребител</h1>

<div>
    <hr />
    <br />
    <dl class="row">

        <dt class="col-sm-4">

            @Html.DisplayNameFor(model => model.Id)

        </dt>

        <dd class="col-sm-10">

            @Html.DisplayFor(model => model.Id)

        </dd>

        <dt class="col-sm-4">

            @Html.DisplayNameFor(model => model.Name)

        </dt>

        <dd class="col-sm-10">

            @Html.DisplayFor(model => model.Name)

        </dd>

        <dt class="col-sm-4">

            @Html.DisplayNameFor(model => model.LastName)

        </dt>

        <dd class="col-sm-10">

            @Html.DisplayFor(model => model.LastName)

        </dd>

        <dt class="col-sm-4">

            @Html.DisplayNameFor(model => model.Email)

        </dt>

        <dd class="col-sm-10">

            @Html.DisplayFor(model => model.Email)

        </dd>

        <dt class="col-sm-4">

            @Html.DisplayNameFor(model => model.UserName)

        </dt>

        <dd class="col-sm-10">

            @Html.DisplayFor(model => model.UserName)

        </dd>

        <dt class="col-sm-4">

            @Html.DisplayNameFor(model => model.PhoneNumber)

        </dt>

        <dd class="col-sm-10">

            @Html.DisplayFor(model => model.PhoneNumber)

        </dd>

        <dt class="col-sm-4">

            @Html.DisplayNameFor(model => model.EGN)

        </dt>

        <dd class="col-sm-10">

            @Html.DisplayFor(model => model.EGN)

        </dd>
    </dl>
</div>
<div>

    <a class="btn btn-success col-md-1" asp-action="Index"><img src="~/images/arrowLeft.png" width="20" /></a>

    <button type="button" class="btn btn-danger col-md-1" data-toggle="modal" data-target="#DeleteUser">Изтрий</button>

    <div id="DeleteUser" class="modal fade" role="dialog">

        <div class="modal-dialog">

            <div class="modal-content">

                <div class="modal-header">

                    <h4 class="modal-title" id="delete-question"> Сигурни ли сте, че искате да го изтриете?</h4>

                    <button type="button" class="close" data-dismiss="modal">&times;</button>

                </div>

                <form asp-action="Delete">

                    <input type="hidden" asp-for="Id" />

                    <input type="submit" value="Delete" class="btn btn-danger" /> |

                    <a asp-action="Index">Назад</a>

                </form>
                <div class="modal-footer">

                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Затвори</button>

                    <form asp-action="Delete">

                        <input type="submit" value="Изтрий" class="btn btn-danger" asp-action="Delete" asp-route-id="@Model.Id" />

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Areas/Admin/Views/ApplicationUser/Details.cshtml
@model Ciel.Models.ApplicationUser

@{

    ViewData["Title"] = "Детайли-потребител";

}

<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Детайли за потребител</title>

    <style>

        body {
            font-family: Arial, sans-serif;
            background-color: #f8f9fa;
            margin: 0;
            padding: 0;
        }

        .container {
            width: 80%;
            margin: 0 auto;
            padding: 20px;
        }

        .details {
            background-color: #f0f0f0;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            margin-bottom: 20px;
        }

            .details h1 {
                color: #333;
                font-size: 24px;
                margin-bottom: 10px;
                text-align: center;
            }

            .details dl.row {
                display: flex;
                flex-wrap: wrap;
                justify-content: space-between;
            }

            .details dt.col-sm-4 {
                flex: 0 0 30%;
                max-width: 30%;
                color: #666;
                font-weight: bold;
                margin-bottom: 10px;
            }

            .details dd.col-sm-10 {
                flex: 0 0 65%;
                max-width: 65%;
                color: #333;
                margin-bottom: 10px;
            }

        .button-row {
            display: flex;
            justify-content: space-between;
            margin-top: 20px;
        }

            .button-row button {
                background-color: #dc3545;
                color: #fff;
                padding: 10px 20px;
                border-radius: 5px;
                border: none;
                cursor: pointer;
            }

                .button-row button:hover {
                    background-color: #c82333;
                }

    </style>

</head>
<script>
    function confirmDelete() {
        var result = confirm("Сигурни ли сте, че искате да изтриете този потребител?");
        if (result) {
            document.getElementById('deleteUserForm').submit();
        }
    }
</script>

<body>

    <div class="container">

        <div class="details">

            <h1>Детайли за потребител</h1>

            <hr>

            <dl class="row">

                <dt class="col-sm-4">

                    <p>Потребителски номер</p>

                </dt>

                <dd class="col-sm-10">

                    @Html.DisplayFor(model => model.Id)

                </dd>

                <dt class="col-sm-4">

                    <p>Име</p>

                </dt>

                <dd class="col-sm-10">

                    @Html.DisplayFor(model => model.Name)

                </dd>

                <dt class="col-sm-4">

                    <p>Фамилия</p>

                </dt>

                <dd class="col-sm-10">

                    @Html.DisplayFor(model => model.LastName)

                </dd>

                <dt class="col-sm-4">

                    <p>Имейл</p>

                </dt>

                <dd class="col-sm-10">

                    @Html.DisplayFor(model => model.Email)

                </dd>

                <dt class="col-sm-4">

                    <p>Потребителско име</p>

                </dt>

                <dd class="col-sm-10">

                    @Html.DisplayFor(model => model.UserName)

                </dd>

                <dt class="col-sm-4">

                    <p>Телефонен номер</p>

                </dt>

                <dd class="col-sm-10">

                    @Html.DisplayFor(model => model.PhoneNumber)

                </dd>

                <dt class="col-sm-4">

                    <p>ЕГН</p>

                </dt>

                <dd class="col-sm-10">

                    @Html.DisplayFor(model => model.EGN)

                </dd>

            </dl>

            <form id="deleteUserForm" asp-controller="ApplicationUser" asp-action="Delete">

                <input type="hidden" value="@ViewData["userId"]" id="userId" name="id" />

                <button type="button" class="btn btn-danger" onclick="confirmDelete()">Изтрий</button>

                <a type="button" asp-action="Index" class="btn btn-secondary" data-dismiss="modal">Откажи</a>

            </form>

        </div>

    </div>

</body>

</html>

Areas/Admin/Views/ApplicationUser/Edit.cshtml
@model Ciel.Models.ApplicationUser
<head>
	<link rel="stylesheet" href="~/css/UserEdit.css" asp-append-version="true" />
</head>

<div class="center-text">
	<h1 class="styled-header">Редактиране на потребител</h1>
</div>

<form asp-action="Edit">
	<input type="hidden" asp-for="Id" />
	<div class="form-group">
		<label asp-for="Name"></label>
		<input asp-for="Name" class="form-control" />
		<span asp-validation-for="Name" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="LastName"></label>
		<input asp-for="LastName" class="form-control" />
		<span asp-validation-for="LastName" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="Email">Имейл</label>
		<input asp-for="Email" class="form-control" />
		<span asp-validation-for="Email" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="UserName">Потребителско име</label>
		<input asp-for="UserName" class="form-control" />
		<span asp-validation-for="UserName" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="PhoneNumber">Телефонен Номер</label>
		<input asp-for="PhoneNumber" class="form-control" />
		<span asp-validation-for="PhoneNumber" class="text-danger"></span>
	</div>
	<div class="form-group">
		<label asp-for="EGN"></label>
		<input asp-for="EGN" class="form-control" />
		<span asp-validation-for="EGN" class="text-danger"></span>
	</div>
	<div style="height: 30px;"></div>
	<center>
		<button class="btn btn-outline-dark" type="submit"> <i class="bi bi-cloud-download"></i> Запази промените</button>
		<button class="btn btn-outline-dark" type="submit" asp-action="Index"><i class="bi bi-arrow-bar-left"></i> Назад</button>
	</center>
</form>
<div style="height: 100px;"></div>

Areas/Admin/Views/ApplicationUser/Index.cshtml
@model IEnumerable<Ciel.Models.ApplicationUser>

@{

    ViewData["Title"] = "Потребители";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Списък за потребители</title>
</head>
<body>
    <div class="container">
        <center>
        <h1>Списък за потребители</h1>
		</center>
        <div class="overflow-auto">
            <table class="table table-hover">
                <thead>
                    <tr class="bg-success text-center" style="background-color: black !important;">
                        <th class="text-light">

                            Име

                        </th>
                        <th class="text-light">

                            Фамилия

                        </th>

                        <th class="text-light">

                            Имейл

                        </th>

                        <th class="text-light">

                            Телефонен номер

                        </th>

                        <th class="text-light">

                        </th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model)

                    {

                        <tr class="table-light text-center">

                            <td>

                                @Html.DisplayFor(modelItem => item.Name)

                            </td>

                            <td>

                                @Html.DisplayFor(modelItem => item.LastName)

                            </td>

                            <td>

                                @Html.DisplayFor(modelItem => item.Email)

                            </td>

                            <td>

                                @Html.DisplayFor(modelItem => item.PhoneNumber)

                            </td>

                            <td>

                                <a class="btn btn-outline-dark" asp-action="Details" asp-route-id="@item.Id">Детайли</a>
                                <a class="btn btn-outline-dark" asp-action="Edit" asp-route-id="@item.Id">Редактирай</a>

                            </td>

                        </tr>
                    }
                </tbody>
            </table>
        </div>
      
        <center>
            <a class="btn btn-outline-dark" asp-area="" asp-controller="Home" asp-action="Index" class="back-button"> <i class="bi bi-arrow-bar-left"></i> Назад</a>
            <a class="btn btn-outline-dark" asp-action="Create" asp-controller="ApplicationUser"><i class="bi bi-person-plus"></i> Създай</a>
        </center>
    </div>

</body>
</html>